version: '3'
services:
  db:
    image: postgres
    container_name: dl-loan-data
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: loan_performance
      POSTGRES_USER: gwu-dl-user
      POSTGRES_PASSWORD: Gw_ml2_@
    ports:
     - 5432:5432

  python:
    image: gwu-dl-py
    container_name: anaconda
    depends_on:
      - db
    build: .
    volumes:
      - ~/raw_data:/app/raw_data
      - ~/pickles:/app/pickles
    environment:
      DB_HOST: db
    command: python pre_process_main.py --dry_run --check --host db

